import argparse
import numpy as np
import sys
from src.planners.plannerRNN import run_diffusion_planner

import jax


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--env_name", type=str, default="Craftax-Symbolic-v1")
    parser.add_argument("--num_envs", type=int, default=1024)
    parser.add_argument("--total_timesteps", type=lambda x: int(float(x)), default=1e9)
    parser.add_argument("--lr", type=float, default=2e-4)
    parser.add_argument("--num_steps", type=int, default=64)
    parser.add_argument("--update_epochs", type=int, default=4)
    parser.add_argument("--num_minibatches", type=int, default=8)
    parser.add_argument("--gamma", type=float, default=0.99)
    # REMOVED: --gae_lambda (not used; replaced by MC returns)
    # REMOVED: --clip_eps (no PPO clipping in diffusion loss)
    # REMOVED: --ent_coef (no explicit entropy bonus; diversity
    #          comes from the stochastic diffusion sampling)
    parser.add_argument("--vf_coef", type=float, default=0.5)
    parser.add_argument("--max_grad_norm", type=float, default=1.0)
    parser.add_argument("--activation", type=str, default="tanh")
    parser.add_argument(
        "--anneal_lr", action=argparse.BooleanOptionalAction, default=True
    )
    parser.add_argument("--debug", action=argparse.BooleanOptionalAction, default=True)
    parser.add_argument("--jit", action=argparse.BooleanOptionalAction, default=True)
    parser.add_argument("--seed", type=int, default=np.random.randint(2**31))
    parser.add_argument(
        "--use_wandb", action=argparse.BooleanOptionalAction, default=True
    )
    parser.add_argument(
        "--save_policy", action=argparse.BooleanOptionalAction, default=False
    )
    parser.add_argument("--num_repeats", type=int, default=1)
    parser.add_argument("--layer_size", type=int, default=512)
    parser.add_argument("--wandb_project", type=str)
    parser.add_argument("--wandb_entity", type=str)
    parser.add_argument(
        "--use_optimistic_resets", action=argparse.BooleanOptionalAction, default=True
    )
    parser.add_argument("--optimistic_reset_ratio", type=int, default=16)

    # ─── NEW: diffusion-specific hyperparameters ───
    parser.add_argument(
        "--plan_horizon", type=int, default=8,
        help="Length of the action plan generated by the denoiser",
    )
    parser.add_argument(
        "--num_diff_steps", type=int, default=16,
        help="Number of reverse-process denoising steps (T)",
    )
    parser.add_argument(
        "--plan_embed_dim", type=int, default=32,
        help="Embedding dimension per action token in the plan",
    )
    parser.add_argument(
        "--remask_eta", type=float, default=0.1,
        help="ReMDM remasking rate η  (0 = no remasking = vanilla masked diffusion)",
    )
    parser.add_argument(
        "--sample_temperature", type=float, default=1.0,
        help="Temperature for categorical sampling during reverse process",
    )
    parser.add_argument(
        "--adv_temperature", type=float, default=1.0,
        help="Temperature for advantage-based exponential weighting of diffusion loss",
    )

    args, rest_args = parser.parse_known_args(sys.argv[1:])
    if rest_args:
        raise ValueError(f"Unknown args {rest_args}")

    if args.seed is None:
        args.seed = np.random.randint(2**31)

    if args.jit:
        run_diffusion_planner(args)
    else:
        with jax.disable_jit():
            run_diffusion_planner(args)